### ISSUE TITLE
HCELEC-395 metadata district does not allow null value

### ISSUE THREAD

**Issue by KuzminaAnna** [GlobalPathogenAnalysisService/gpas-cli#42]
**Describe the problem/error:** If the user tries to upload metadata with null value in district column on gpas-cli, the terminal throws error: district can only contain characters (a-Za-z0-9:_-).

**Expected behavior:** If the user tries to upload metadata with null value in district column, gpas-cli should successfully accept the file without any error.

**Steps to Reproduce:**  

Upload a meatadata with null value in district
**System Identification:** DEV
**Reproducible?** Yes
**If multiple areas are impacted list areas:** gpas-cli
**If compatibility/interoperability is impacted list products (e.g.):** N/A
**If this is a customer issue list name:** N/A
![Screen Shot 2022-06-30 at 3 44 01 PM](https://user-images.githubusercontent.com/24322003/176906867-2ff3ad42-d3fd-41dd-9719-eed031e53004.png)

**Comment by natesun1** [comment]
I just tested again on 0.1.3 version, and I am still able to reproduce. I believe any csv file would work just make sure district is null.


I tried to re-test with the latest version 0.2.1 but got some error when installing gpas-cli. 
![Screen Shot 2022-07-06 at 11 09 54 AM](https://user-images.githubusercontent.com/102683639/177596064-171b0861-68da-4812-b150-75577cb4b605.png)

**Comment by bede** [comment]
I've just checked out and installed 0.1.3 and my empty district test passes fine. Please can you use the same CSV, which is in the repo inside test-data, and confirm?
```
Successfully installed gpas-0.1.3
(gpas-cli-dev) bede@dhcpjr27 gpas-cli % gpas validate tests/test-data/empty-district.csv 
INFO: Validation successful
```

**Comment by natesun1** [comment]
I have already deleted 0.1.3 on linux 20 and tried to install 0.2.1 version so I can not re-test anything related to 0.1.3. Also as I understand we will not release 0.1.3 and I was told to test only the latest version, in this case 0.2.1

**Comment by natesun1** [comment]
UPDATE: this issue is also reproducible with nanopore samples, in order to recreate the issue user needs to have more than 1 samples inside metadata, and the first sample district can not be null, leave the other district values as null and will see the error.

**Comment by bede** [comment]
Hi Nate,
I have created a CSV as you describe which passes validation in 0.2.1. If you would ever like me to reproduce a validation error, please can you provide the actual file to avoid us going around in circles like this?

`empty-district-multiple.csv`:
```
batch,run_number,sample_name,fastq,control,collection_date,tags,country,region,district,specimen_organism,host,primer_scheme,instrument_platform
run1,run1.1,COVID_locost_2_barcode10,reads/large-nanopore-fastq.fastq.gz,,2022-05-06,GPAS_OxUni,USA,Texas,cat,SARS-CoV-2,human,auto,Nanopore
run1,run1.1,unpaired1,reads/nanopore-fastq/unpaired1.fastq.gz,,2022-05-06,GPAS_OxUni,USA,Texas,,SARS-CoV-2,human,auto,Nanopore
```

**Comment by natesun1** [comment]
Hi Bede,

I am very sorry for the back-and-forth and frustration, I thought the any use is able to reproduce the issue easily but looks like my data is a very edge case scenario. Please take a look of my test data for further troubleshooting. 

[illumina-fastq-happypath.csv](https://github.com/GlobalPathogenAnalysisService/gpas-cli/files/9074187/illumina-fastq-happypath.csv)

**Comment by bede** [comment]
Thanks Nate. The issue here was caused by automatic casting of district value `1124` to an integer dtype during CSV parsing. I have now enforced string coercion for all columns in the upload csv in https://github.com/GlobalPathogenAnalysisService/gpas-cli/commit/c613b42730a30aa7131248d08ce5bb51af76d3d7
