### ISSUE TITLE
HCELEC-399 user can not run gpas-cli on Linux 16 or 18 OS

### ISSUE THREAD

**Issue by KuzminaAnna** [GlobalPathogenAnalysisService/gpas-cli#43]
**Describe the problem/error:** If the user tries to setup gpas-cli on linux 16.04 or 18.04 OS through commend line, the user gets an error: Error loading Python lib.

**Expected behavior:** If the user tries to setup gpas-cli on linux 16.04 or 18.04 OS through commend line, the user should not get any error and successfully complete the setup. 

**Steps to Reproduce:**  

Follow the setup steps from https://github.com/GlobalPathogenAnalysisService/gpas-cli/wiki/Using-the-PyInstaller-binary-distribution to install gpas-cli on Linux 16.04 or 18.04 OS
when running commend line: dist/cli-upload -h, the user gets error about error loading python library. 
**System Identification:** DEV
**Reproducible?** Yes
**If multiple areas are impacted list areas**: gpas-cli
**If compatibility/interoperability is impacted list products (e.g.):** N/A
**![Screen Shot 2022-06-30 at 5 02 15 PM](https://user-images.githubusercontent.com/24322003/177277748-392db475-6eaf-468d-a48d-18293ed5329a.png)** N/A

**Comment by KuzminaAnna** [comment]
We were told by Oxford team that gpas-cli does not support linux version lower than 20, but EC support linux 16 and 18. Does this mean that EC should no longer support older Linux versions?

**Comment by bede** [comment]
Since properly patched ONT GridION instruments will soon be running 20+,
there is no need to support 16, as this was the only prior reason to
support 16.

I’m not sure why 18 isn’t currently working in the pyinstaller version and
should investigate.

Whether to support 18 is a discussion worth having.

**Comment by bede** [comment]
Support for older versions of Linux will only be possible through the CLI. Conda can install new Pythons on old OSs
