### ISSUE TITLE
HCELEC-412 Exception while uploading illumina sample possibly since tag validation did not cover empty tag at subfield level

### ISSUE THREAD

**Issue by KuzminaAnna** [GlobalPathogenAnalysisService/gpas-cli#50]
**Describe the problem/error:** "SubmissionError('Error occurred creating samples: You do not have access to one or more listed tags ["Oracle_Site","OCI",""]'): File "gpas/misc.py", line 110, in jsonify_exceptions , File "gpas/cli-upload.py", line 36, in upload , File "gpas/lib.py", line 823, in upload , File "gpas/lib.py", line 760, in _submit , File "gpas/lib.py", line 741, in _finalise_submission" when uploading illumina file.
**Expected behavior:** Null Tag at the Subfield level should not be allowed and caught in the validation Phase.
**Steps to Reproduce:** 

Take an illumina file with multiple errors and fix all validation Errors by fixing metadata file.

Make sure that there is an empty Tag at the Sub field level.

Upload the file.
**System Identification:** This might be on the CLI side.

**Comment by KuzminaAnna** [comment]
[MultipleBatches.csv](https://github.com/GlobalPathogenAnalysisService/gpas-cli/files/9073351/MultipleBatches.csv)
<img width="1272" alt="Screen Shot 2022-07-08 at 11 29 39 AM" src="https://user-images.githubusercontent.com/24322003/178026377-8cb8d312-3889-48c8-888c-9a0bdfc43879.png">

**Comment by bede** [comment]
Would it be possible to have an upload csv in order to replicate? Don't worry about the reads as I can substitute those quite easily

**Comment by bede** [comment]
Please ignore above comment – I understand how to reproduce. Thanks for reporting!

**Comment by bede** [comment]
The case of MultipleBatches.csv is actually expected behaviour – empty tags are meant to be removed and thus not raise a ValidationError. However I did find an edge case where an empty tag sandwiched by non-empty tags would lead to an empty tag failing to be stripped, and I have now fixed this along with a several new tests locking down this behaviour. I will commit this code shortly.

**Comment by bede** [comment]
This has been committed to main
