### ISSUE TITLE
HCELEC-413 error message is not implicit when sample name is null or empty	

### ISSUE THREAD

**Issue by KuzminaAnna** [GlobalPathogenAnalysisService/gpas-cli#52]
**Describe the problem/error:** When the sample name within metadata is null or empty, user is expected to see error message "Unknown error occurred: sample_name cannot be empty", but actual user sees "TypeError("unsupported operand type(s) for +:'NonType' and 'str'"):File "gpas/misc.py"", this message is not direct and does not indicate for the user how to fix the metadata. 

Besides EC, I also tested gpas-cli 0.2.1, saw the same error, suggesting this issue might rise from gpas-cli side.

**Expected behavior:** When the sample name within metadata is null or empty, user is expected to see error message "Unknown error occurred: sample_name cannot be empty".

**Steps to Reproduce:**  

Upload a meatadata with sample name null or empty through EC
Expect the validation to throw error "Unknown error occurred: sample_name cannot be empty". Actual the error "TypeError("unsupported operand type(s) for +:'NonType' and 'str'"):File "gpas/misc.py""
The output should be a validation error, not
[illumina-fastq-upload_sample_name_empty.csv](https://github.com/GlobalPathogenAnalysisService/gpas-cli/files/9082264/illumina-fastq-upload_sample_name_empty.csv)
![Screen Shot 2022-07-08 at 4 28 48 PM](https://user-images.githubusercontent.com/24322003/178224237-38df2c7f-802a-408c-a403-3339854a1c0b.png)
![Screen Shot 2022-07-08 at 4 44 39 PM](https://user-images.githubusercontent.com/24322003/178224242-5dcb1302-7cde-4cf3-9081-3a4a5bc8caad.png)
 a general exception.
**System Identification:** DEV
**Reproducible?** Yes
**If multiple areas are impacted list areas:** EC 1.0.9 integrated with gpas-cli 0.2.1

**Comment by bede** [comment]
Added two new errors and corresponding tests:
- `sample_name must be unique` 
- `sample_name cannot be empty`

`sample_name must be unique`  is for the time being accompanied by an automatically enumerated numerical `sample_name`.

```
{
        "sample_name": 1,
        "error": "sample_name must be unique",
}
```
