### ISSUE TITLE
EC 1.1.4: "sample_name must be unique" error message is not returned to the user if metadata contains invalid platform

### ISSUE THREAD

**Issue by KuzminaAnna** [GlobalPathogenAnalysisService/gpas-cli#95]
**Describe the problem/error:** If a metadata contains non-unique sample names in-addition to invalid instrument_platform values, "sample_name must be unique" error message is not returned to the user. Instead only error message about invalid instrument_platform is returned to the user.
**Expected behaviour:** "sample_name must be unique" error message should be returned to the user in-addition to other invalid errors

**Steps to Reproduce:**

- Upload attached metadata. [illumina-fastq-upload_sample_name_same_invalid_platfrom.csv] (NOTE: don't forget to add .fastq.gz files.)
- Verify error message

**System Identification:** DEV
**Reproducible?** Yes
**If multiple areas are impacted list areas:** Electron client 1.1.4 all platforms. 
**If compatibility/interoperability is impacted list products (e.g.):** Gpas Portals.
[illumina-fastq-upload_sample_name_same_invalid_platfrom.csv.zip](https://github.com/GlobalPathogenAnalysisService/gpas-cli/files/10021298/illumina-fastq-upload_sample_name_same_invalid_platfrom.csv.zip)
![Screen Shot 2022-11-15 at 9 04 14 PM](https://user-images.githubusercontent.com/24322003/202173969-c70fbba6-e3c7-4e9f-b449-49389a394e12.png)

**Comment by bede** [comment]
This is expected behaviour – schema selection is a necessary pre-validation step prior to the main, lazily evaluated validation process. However, I have made it trigger a ValidationError to avoid confusion.
